# Generated by Django 6.0.4 on 2026-05-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name="Ссылка платежа"),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID сессии"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(blank=True, max_length=30, null=True, verbose_name="Сумма платежи"),
        ),
    ]
