# Generated by Django 6.0.4 on 2026-05-03 14:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_payment_link_payment_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Сумма платежи"),
        ),
    ]
