# Generated by Django 6.0.4 on 2026-05-03 18:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_link",
            field=models.TextField(blank=True, null=True, verbose_name="Ссылка платежа"),
        ),
    ]
