# Generated by Django 6.0.4 on 2026-05-04 13:52

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payment_payment_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("paid", "Оплачен"), ("unpaid", "Не оплачен")], default="unpaid", max_length=10
            ),
        ),
    ]
