# Generated by Django 6.0.4 on 2026-04-17 16:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание урока"),
        ),
    ]
