# Generated by Django 6.0.4 on 2026-04-30 14:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_url",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка на курс"),
        ),
    ]
