# Generated by Django 6.0.4 on 2026-04-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0007_coursesubscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursesubscription",
            name="is_active",
        ),
    ]
