# Generated by Django 6.0.4 on 2026-05-03 10:20

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0008_remove_coursesubscription_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(blank=True, max_length=30, null=True, verbose_name="Цена курса"),
        ),
    ]
