# Generated by Django 6.0.4 on 2026-05-03 14:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0009_course_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(default=15000, verbose_name="Цена курса"),
        ),
    ]
